version: '3'

services:
  web:
    image: nginx
    restart: always
    ports:
      - 192.168.51.129:80:80
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      net:
        ipv4_address: 10.5.0.4
  bind-master:
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    ports:
      - 192.168.51.220:53:53/udp
      - 192.168.51.220:53:53/tcp
    volumes:
      - ./master:/etc/bind
      - ./master/zones:/var/lib/bind
    networks:
      net:
        ipv4_address: 10.5.0.2
  bind-slave:
    image: internetsystemsconsortium/bind9:9.18
    restart: always
    ports:
      - 192.168.51.124:53:53/udp
      - 192.168.51.124:53:53/tcp
    volumes:
      - ./slave:/etc/bind
      - ./slave/zones:/var/lib/bind
    networks:
      net:
        ipv4_address: 10.5.0.3

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1